import {conversionModes,accepts,convertFile,picturesToYtd} from './converter.js';
import {zipFiles,MAX_EXPORT,safePath} from './asset-tools.js';
import {clothingInfo,importPath,analyzePack,buildPack} from './clothing-pack.js';
export function mountTools({download,toast,preview,confirmDiscard}){
 const $=id=>document.getElementById(id),editor=document.querySelector('main'),viewer=document.querySelector('.right'),home=viewer.parentElement;
 const nav=document.createElement('nav');nav.className='workspace-nav';nav.setAttribute('aria-label','Workspace tools');nav.innerHTML='<button data-page="editor" class="active">Texture & Model</button><button data-page="converter">Converter</button><button data-page="pack">Clothing pack</button>';
 document.querySelector('header').after(nav);
 const root=document.createElement('section');root.className='tool-workspace';root.hidden=true;root.innerHTML=`
 <aside class="tool-sidebar"><span class="eyebrow" id="toolEyebrow"></span><h2 id="toolHeading"></h2>
 <div id="convertSettings"><label>Konversi<select id="conversionMode"></select></label><p id="conversionHint" class="muted"></p><label>Nama YTD<input id="dictionaryName" value="ditasha_textures"></label><p class="muted">YTD / DDS: tanpa kompresi, satu mipmap. GLB: mesh & UV saja; tanpa rig, animasi atau material GTA.</p></div>
 <div id="packSettings" hidden><label>Nama resource<input id="packName" value="ditasha_clothing" maxlength="64"></label><label>Mode pack<select id="packMode"><option value="replace">Replacement clothing</option><option value="addon">Existing add-on collection</option></select></label><p class="muted" id="packHint">Nama file menentukan ped dan slot replacement.</p><label>Catatan build<textarea id="packNote" rows="3" placeholder="Apa yang berubah?"></textarea></label></div>
 <div class="tool-buttons"><button id="toolAdd">＋ File</button><button id="toolFolder">Folder</button><button id="toolClear">Kosongkan</button></div><input id="toolFileInput" type="file" multiple hidden><input id="toolFolderInput" type="file" webkitdirectory multiple hidden>
 <input id="toolSearch" class="search" placeholder="Cari file…" aria-label="Cari file tools"><select id="packFilter" aria-label="Filter ped" hidden><option value="All">All</option><option>Male</option><option>Female</option><option>Unknown</option></select><div id="toolQueue"></div><p id="toolCount" class="muted"></p></aside>
 <section class="tool-center"><div id="toolEmpty" class="empty"><span class="emptykicker">DITASHA WORKSHOP</span><h3 id="toolEmptyTitle">Drop files here</h3><p id="toolEmptyHelp"></p><button id="toolChoose" class="primary">Pilih file</button></div><div id="packViewer"></div><div id="convertResults" hidden><h2>Hasil konversi</h2><p class="muted">Pilih simpan untuk setiap hasil, atau simpan semuanya sebagai ZIP.</p><div id="outputFiles"></div></div></section>
 <aside class="tool-details"><span class="eyebrow">DETAILS</span><h2 id="toolDetailsHeading">Siap memulai</h2><p id="toolDetailsText" class="muted"></p><label id="packPathLabel" hidden>Path ekspor<input id="packPath"></label><button id="packPreview" hidden>Lihat model 3D</button><div id="packStats" class="pack-stats" hidden></div><h3>Findings</h3><ul id="toolFindings"></ul><p id="toolStatus" role="status"></p><progress id="toolProgress" hidden></progress><div class="tool-bottom"><button id="toolRun" class="primary" disabled>Convert</button><button id="saveAll" hidden>Simpan semua (ZIP)</button><p class="muted" id="toolSaved"></p></div></aside>`;
 nav.after(root);
 for(const [id,title] of conversionModes){const o=document.createElement('option');o.value=id;o.textContent=title;$('conversionMode').append(o);}
 let page='editor',queue=[],pack=[],outputs=[],selection=null,busy=false,revision=0,savedRevision=0,buildVersion=1;
 const dirty=()=>pack.length&&revision!==savedRevision;
 const touch=()=>{revision++;$('toolSaved').textContent='Perubahan pack belum diekspor.';};
 const mode=()=>$('conversionMode').value;
 function activate(next){if(busy)return;if(page!==next)selection=null;page=next;editor.hidden=next!=='editor';root.hidden=next==='editor';nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.page===next));if(next==='editor'){home.append(viewer);return;}
 const isPack=next==='pack';$('convertSettings').hidden=isPack;$('packSettings').hidden=!isPack;$('packFilter').hidden=!isPack;$('toolFolder').hidden=!isPack;$('toolEyebrow').textContent=isPack?'FIVEM RESOURCE':'BATCH CONVERTER';$('toolHeading').textContent=isPack?'Clothing pack':'Converter';$('toolEmptyTitle').textContent=isPack?'Drop clothing here':'Drop files here';$('toolEmptyHelp').textContent=isPack?'YDD + YTD. Add-on: sertakan YMT dan shop .meta. Import file atau folder resource.':'Tambahkan file untuk konversi lokal. Hasil dapat disimpan satu per satu atau sebagai ZIP.';$('toolRun').textContent=isPack?'Build pack ZIP':'Convert';$('toolSaved').hidden=!isPack;$('toolStatus').textContent=isPack?'Siap membangun pack.':outputs.length?'Hasil siap disimpan.':'Tambahkan file untuk konversi.';$('toolFileInput').accept=isPack?'.ydd,.ytd,.ymt,.yld,.meta':mode()==='glb'?'.ydd,.ydr,.yft,.obj,.stl':'.png,.jpg,.jpeg,.webp,.dds,.ytd';if(isPack)$('packViewer').append(viewer);else home.append(viewer);$('packViewer').hidden=!isPack;root.classList.toggle('is-pack',isPack);render();}
 nav.querySelectorAll('button').forEach(b=>b.onclick=()=>activate(b.dataset.page));
 function findings(messages){$('toolFindings').replaceChildren();for(const text of messages){const li=document.createElement('li');li.textContent=text;$('toolFindings').append(li);}}
 function render(){if(page==='editor')return;const isPack=page==='pack',list=isPack?pack:queue,q=$('toolSearch').value.toLowerCase();$('toolQueue').replaceChildren();const filtered=list.filter(e=>(e.path||e.file.name).toLowerCase().includes(q)&&(!isPack||$('packFilter').value==='All'||clothingInfo(e.path).gender===$('packFilter').value));const groups=new Map();for(const e of filtered){const group=isPack?clothingInfo(e.path).gender+' · '+clothingInfo(e.path).slot:'FILES';if(!groups.has(group))groups.set(group,[]);groups.get(group).push(e);}for(const [group,items] of groups){const title=document.createElement('h3');title.className='queue-group';title.textContent=group+' · '+items.length;$('toolQueue').append(title);for(const e of items){const row=document.createElement('div');row.className='tool-file';const b=document.createElement('button');b.textContent=e.path||e.file.name;b.title=b.textContent;b.classList.toggle('selected',e===selection);b.onclick=()=>{if(busy)return;selection=e;render();};const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','Hapus '+b.textContent);del.onclick=()=>{if(busy)return;list.splice(list.indexOf(e),1);if(isPack)touch();if(selection===e)selection=null;render();};row.append(b,del);$('toolQueue').append(row);}}
 $('toolCount').textContent=list.length+' file · '+(list.reduce((n,e)=>n+(isPack?e.data.length:e.file.size),0)/1048576).toFixed(1)+' MB';$('toolEmpty').hidden=isPack||outputs.length>0;$('convertResults').hidden=isPack||!outputs.length;$('saveAll').hidden=isPack||!outputs.length;$('packStats').hidden=!isPack;$('packPathLabel').hidden=!isPack||!selection;$('packPreview').hidden=!isPack||!selection||!selection.path.toLowerCase().endsWith('.ydd');$('toolDetailsHeading').textContent=selection?(selection.path||selection.file.name).split('/').at(-1):'Siap memulai';$('toolDetailsText').textContent=selection?isPack?clothingInfo(selection.path).key:(selection.file.size/1024).toFixed(0)+' KB':'Pilih file untuk melihat detail.';
 if(isPack){if(selection)$('packPath').value=selection.path;$('packPath').disabled=$('packMode').value==='addon';const check=analyzePack(pack,$('packMode').value);$('packStats').replaceChildren();for(const [title,n] of [['Models',check.models],['Textures',check.textures],['YMT',check.ymts],['Shop meta',check.metas]]){const tile=document.createElement('div'),small=document.createElement('small'),strong=document.createElement('strong');small.textContent=title;strong.textContent=n;tile.append(small,strong);$('packStats').append(tile);}findings([...check.errors,...check.warnings]);$('toolRun').disabled=busy||check.errors.length>0||!pack.length;$('packHint').textContent=$('packMode').value==='addon'?'YMT dan shop .meta wajib. Collection ID dan nama file dipertahankan. Tidak membuat YMT baru.':'Nama file menentukan ped dan slot replacement. Prefix mp_m_freemode_01 / mp_f_freemode_01 wajib.';}else{findings(queue.filter(e=>!accepts(mode(),e.file.name)).map(e=>'Input tidak sesuai: '+e.file.name));$('toolRun').disabled=busy||!queue.length||queue.some(e=>!accepts(mode(),e.file.name));}
 }
 function setBusy(value){busy=value;root.querySelectorAll('input,select,textarea,button').forEach(e=>e.disabled=value);nav.querySelectorAll('button').forEach(e=>e.disabled=value);$('toolProgress').hidden=!value;if(!value)render();}
 async function add(files){if(busy)return;setBusy(true);let skipped=0;try{if(page==='pack'){let total=pack.reduce((n,e)=>n+e.data.length,0);for(const file of files){if(!/\.(ydd|ytd|ymt|yld|meta)$/i.test(file.name)){skipped++;continue;}if(file.size>64*1024*1024||total+file.size>MAX_EXPORT-65536)throw Error('Pack maksimum 128 MB, setiap file maksimum 64 MB.');const path=importPath(file.webkitRelativePath||file.name);if(pack.some(e=>e.path.toLowerCase()===path.toLowerCase()))throw Error('File duplikat: '+path);const data=new Uint8Array(await file.arrayBuffer());if(/\.(ydd|ytd|yld)$/i.test(path)&&(data.length<16||new DataView(data.buffer).getUint32(0,true)!==0x37435352))throw Error('Resource RSC7 tidak valid: '+path);if(/\.meta$/i.test(path)){const xml=new DOMParser().parseFromString(new TextDecoder().decode(data),'application/xml');if(xml.querySelector('parsererror')||xml.documentElement.tagName!=='ShopPedApparel')throw Error('File harus shop apparel XML: '+path);}pack.push({path,data,file});total+=data.length;touch();}}else for(const file of files){if(file.size>64*1024*1024)throw Error('File maksimum 64 MB.');if(queue.length>=256||queue.reduce((n,e)=>n+e.file.size,0)+file.size>MAX_EXPORT)throw Error('Batch maksimum 256 file / 128 MB.');queue.push({file});}if(skipped)toast(skipped+' file non-clothing dilewati.');$('toolStatus').textContent='File ditambahkan.';}catch(e){toast(e.message);$('toolStatus').textContent=e.message;}finally{setBusy(false);}}
 $('toolAdd').onclick=$('toolChoose').onclick=()=>$('toolFileInput').click();$('toolFolder').onclick=()=>$('toolFolderInput').click();for(const id of ['toolFileInput','toolFolderInput'])$(id).onchange=async e=>{await add([...e.target.files]);e.target.value='';};$('toolSearch').oninput=$('packFilter').onchange=render;
 $('conversionMode').onchange=()=>{outputs=[];updateHint();activate('converter');};function updateHint(){$('conversionHint').textContent=conversionModes.find(m=>m[0]===mode())[2];$('dictionaryName').parentElement.hidden=mode()!=='ytd';}updateHint();
 $('toolClear').onclick=async()=>{if(busy)return;if(page==='pack'){if(dirty()&&await confirmDiscard('pack', [{name:'Clothing pack · '+$('packName').value}])!=='discard')return;pack=[];selection=null;touch();}else{queue=[];outputs=[];selection=null;}render();};
 for(const id of ['packName','packMode','packNote'])$(id).oninput=()=>{if(pack.length)touch();render();};$('packPath').onchange=()=>{if(!selection||busy||$('packMode').value==='addon')return;try{const path=safePath($('packPath').value);if(!path.startsWith('stream/')||!path.toLowerCase().endsWith('.'+selection.file.name.split('.').at(-1).toLowerCase()))throw Error('Simpan asset ke stream/ dan pertahankan ekstensi.');selection.path=path;touch();render();}catch(e){toast(e.message);render();}};
 $('packPreview').onclick=async()=>{if(!selection||busy)return;const e=selection;setBusy(true);try{const paired=pack.find(t=>/\.ytd$/i.test(t.path)&&clothingInfo(t.path).key===clothingInfo(e.path).key);await preview([e,...(paired?[paired]:[])].map(t=>new File([t.data],t.path.split('/').at(-1))));toast('Model dimuat. Gunakan Perbesar 3D untuk melihat lebih luas.');}finally{setBusy(false);}};
 function renderOutputs(){$('outputFiles').replaceChildren();for(const out of outputs){const row=document.createElement('div');row.className='output-file';const text=document.createElement('span');text.textContent=out.name+' · '+(out.data.length/1024).toFixed(0)+' KB';const b=document.createElement('button');b.textContent='Simpan';b.onclick=async()=>{if(busy)return;setBusy(true);try{const saved=await download(out.data,out.name.split('/').at(-1),'application/octet-stream');b.textContent=saved?'Tersimpan':'Simpan';$('toolStatus').textContent=saved?'File tersimpan.':'Simpan dibatalkan.';}catch(e){toast(e.message);}finally{setBusy(false);}};row.append(text,b);$('outputFiles').append(row);}}
 $('toolRun').onclick=async()=>{if(busy)return;setBusy(true);$('toolStatus').textContent='Memproses…';try{await new Promise(r=>setTimeout(r,25));if(page==='pack'){const bytes=buildPack(pack,{name:$('packName').value,mode:$('packMode').value,note:$('packNote').value,version:buildVersion});const saved=await download(bytes,$('packName').value+'-v'+buildVersion+'.zip','application/zip');if(saved){savedRevision=revision;buildVersion++;$('toolSaved').textContent='Pack tersimpan.';}else $('toolSaved').textContent='Simpan dibatalkan; pack belum diekspor.';}else{outputs=[];if(mode()==='ytd'){const name=$('dictionaryName').value;if(!/^[a-z0-9_-]{1,64}$/.test(name))throw Error('Nama YTD: a–z, angka, _ atau -.');outputs=await picturesToYtd(queue.map(e=>e.file),name);}else{let total=0;for(let i=0;i<queue.length;i++){$('toolStatus').textContent='Konversi '+(i+1)+' / '+queue.length+'…';await new Promise(r=>setTimeout(r,0));const converted=await convertFile(queue[i].file,mode());total+=converted.reduce((n,e)=>n+e.data.length,0);if(total>MAX_EXPORT)throw Error('Hasil batch melebihi 128 MB.');outputs.push(...converted);}}renderOutputs();$('toolStatus').textContent=outputs.length+' hasil siap disimpan.';}}catch(e){$('toolStatus').textContent=e.message;toast(e.message);if(page==='converter'){outputs=[];renderOutputs();}}finally{setBusy(false);}};
 $('saveAll').onclick=async()=>{if(busy)return;setBusy(true);try{const saved=await download(zipFiles(outputs),'ditasha-converted.zip','application/zip');$('toolStatus').textContent=saved?'ZIP tersimpan.':'Simpan dibatalkan.';}catch(e){toast(e.message);}finally{setBusy(false);}};
 document.addEventListener('drop',e=>{if(page==='editor')return;e.preventDefault();e.stopImmediatePropagation();$('drop').classList.remove('drag');add([...e.dataTransfer.files]);},true);
 return {unsavedItems:()=>dirty()?[{name:'Clothing pack · '+$('packName').value}]:[],isActive:()=>page!=='editor'};
}
